/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { AddressDto, AddressDtoFromJSON, AddressDtoFromJSONTyped, AddressDtoToJSON } from './AddressDto';

/**
 *
 * @export
 * @interface AddressListDto
 */
export interface AddressListDto {
  /**
   *
   * @type {Array<AddressDto>}
   * @memberof AddressListDto
   */
  data: Array<AddressDto>;
  /**
   *
   * @type {number}
   * @memberof AddressListDto
   */
  pages: number;
}

export function AddressListDtoFromJSON(json: any): AddressListDto {
  return AddressListDtoFromJSONTyped(json, false);
}

export function AddressListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(AddressDtoFromJSON),
    pages: json['pages'],
  };
}

export function AddressListDtoToJSON(value?: AddressListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(AddressDtoToJSON),
    pages: value.pages,
  };
}
