/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddressDto
 */
export interface AddressDto {
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  street: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  streetNumber: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  apartmentNumber?: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  floor?: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof AddressDto
   */
  postcode: string;
}

export function AddressDtoFromJSON(json: any): AddressDto {
  return AddressDtoFromJSONTyped(json, false);
}

export function AddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    street: json['street'],
    streetNumber: json['streetNumber'],
    apartmentNumber: !exists(json, 'apartmentNumber') ? undefined : json['apartmentNumber'],
    floor: !exists(json, 'floor') ? undefined : json['floor'],
    city: json['city'],
    postcode: json['postcode'],
  };
}

export function AddressDtoToJSON(value?: AddressDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    street: value.street,
    streetNumber: value.streetNumber,
    apartmentNumber: value.apartmentNumber,
    floor: value.floor,
    city: value.city,
    postcode: value.postcode,
  };
}
