/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { ArticleDto, ArticleDtoFromJSON, ArticleDtoFromJSONTyped, ArticleDtoToJSON } from './ArticleDto';

/**
 *
 * @export
 * @interface ArticleListDto
 */
export interface ArticleListDto {
  /**
   *
   * @type {Array<ArticleDto>}
   * @memberof ArticleListDto
   */
  data: Array<ArticleDto>;
}

export function ArticleListDtoFromJSON(json: any): ArticleListDto {
  return ArticleListDtoFromJSONTyped(json, false);
}

export function ArticleListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(ArticleDtoFromJSON),
  };
}

export function ArticleListDtoToJSON(value?: ArticleListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(ArticleDtoToJSON),
  };
}
