/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleDto
 */
export interface ArticleDto {
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    id: string;
}

export function ArticleDtoFromJSON(json: any): ArticleDto {
    return ArticleDtoFromJSONTyped(json, false);
}

export function ArticleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'id': json['id'],
    };
}

export function ArticleDtoToJSON(value?: ArticleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
        'id': value.id,
    };
}

