/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CardDto
 */
export interface CardDto {
  /**
   *
   * @type {string}
   * @memberof CardDto
   */
  number?: string;
  /**
   *
   * @type {string}
   * @memberof CardDto
   */
  expirationDate?: string;
  /**
   *
   * @type {string}
   * @memberof CardDto
   */
  securityCode?: string;
}

export function CardDtoFromJSON(json: any): CardDto {
  return CardDtoFromJSONTyped(json, false);
}

export function CardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    number: !exists(json, 'number') ? undefined : json['number'],
    expirationDate: !exists(json, 'expirationDate') ? undefined : json['expirationDate'],
    securityCode: !exists(json, 'securityCode') ? undefined : json['securityCode'],
  };
}

export function CardDtoToJSON(value?: CardDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    number: value.number,
    expirationDate: value.expirationDate,
    securityCode: value.securityCode,
  };
}
