/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateAddressDto
 */
export interface CreateAddressDto {
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  street: string;
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  streetNumber: string;
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  apartmentNumber?: string;
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  floor?: string;
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof CreateAddressDto
   */
  postcode: string;
}

export function CreateAddressDtoFromJSON(json: any): CreateAddressDto {
  return CreateAddressDtoFromJSONTyped(json, false);
}

export function CreateAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAddressDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    street: json['street'],
    streetNumber: json['streetNumber'],
    apartmentNumber: !exists(json, 'apartmentNumber') ? undefined : json['apartmentNumber'],
    floor: !exists(json, 'floor') ? undefined : json['floor'],
    city: json['city'],
    postcode: json['postcode'],
  };
}

export function CreateAddressDtoToJSON(value?: CreateAddressDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    street: value.street,
    streetNumber: value.streetNumber,
    apartmentNumber: value.apartmentNumber,
    floor: value.floor,
    city: value.city,
    postcode: value.postcode,
  };
}
