/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { SubOrderDto, SubOrderDtoFromJSON, SubOrderDtoFromJSONTyped, SubOrderDtoToJSON } from './SubOrderDto';

/**
 *
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {
  /**
   *
   * @type {string}
   * @memberof CreateOrderDto
   */
  addressId: string;
  /**
   *
   * @type {Array<SubOrderDto>}
   * @memberof CreateOrderDto
   */
  subOrders: Array<SubOrderDto>;
  /**
   *
   * @type {string}
   * @memberof CreateOrderDto
   */
  comment: string;
}

export function CreateOrderDtoFromJSON(json: any): CreateOrderDto {
  return CreateOrderDtoFromJSONTyped(json, false);
}

export function CreateOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    addressId: json['addressId'],
    subOrders: (json['subOrders'] as Array<any>).map(SubOrderDtoFromJSON),
    comment: json['comment'],
  };
}

export function CreateOrderDtoToJSON(value?: CreateOrderDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    addressId: value.addressId,
    subOrders: (value.subOrders as Array<any>).map(SubOrderDtoToJSON),
    comment: value.comment,
  };
}
