/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateArticleDto
 */
export interface CreateArticleDto {
  /**
   *
   * @type {string}
   * @memberof CreateArticleDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateArticleDto
   */
  content: string;
}

export function CreateArticleDtoFromJSON(json: any): CreateArticleDto {
  return CreateArticleDtoFromJSONTyped(json, false);
}

export function CreateArticleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json['title'],
    content: json['content'],
  };
}

export function CreateArticleDtoToJSON(value?: CreateArticleDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    content: value.content,
  };
}
