/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DefaultResponseDto
 */
export interface DefaultResponseDto {
  /**
   *
   * @type {string}
   * @memberof DefaultResponseDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof DefaultResponseDto
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof DefaultResponseDto
   */
  path: string;
  /**
   *
   * @type {string}
   * @memberof DefaultResponseDto
   */
  message?: string;
}

export function DefaultResponseDtoFromJSON(json: any): DefaultResponseDto {
  return DefaultResponseDtoFromJSONTyped(json, false);
}

export function DefaultResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultResponseDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    status: json['status'],
    path: json['path'],
    message: !exists(json, 'message') ? undefined : json['message'],
  };
}

export function DefaultResponseDtoToJSON(value?: DefaultResponseDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    status: value.status,
    path: value.path,
    message: value.message,
  };
}
