/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FavouriteDishDto
 */
export interface FavouriteDishDto {
  /**
   *
   * @type {string}
   * @memberof FavouriteDishDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FavouriteDishDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof FavouriteDishDto
   */
  restaurant: string;
}

export function FavouriteDishDtoFromJSON(json: any): FavouriteDishDto {
  return FavouriteDishDtoFromJSONTyped(json, false);
}

export function FavouriteDishDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavouriteDishDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    restaurant: json['restaurant'],
  };
}

export function FavouriteDishDtoToJSON(value?: FavouriteDishDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    restaurant: value.restaurant,
  };
}
