/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  FavouriteDishDto,
  FavouriteDishDtoFromJSON,
  FavouriteDishDtoFromJSONTyped,
  FavouriteDishDtoToJSON,
} from './FavouriteDishDto';

/**
 *
 * @export
 * @interface FavouriteDishListDto
 */
export interface FavouriteDishListDto {
  /**
   *
   * @type {Array<FavouriteDishDto>}
   * @memberof FavouriteDishListDto
   */
  data: Array<FavouriteDishDto>;
  /**
   *
   * @type {number}
   * @memberof FavouriteDishListDto
   */
  pages: number;
}

export function FavouriteDishListDtoFromJSON(json: any): FavouriteDishListDto {
  return FavouriteDishListDtoFromJSONTyped(json, false);
}

export function FavouriteDishListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavouriteDishListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(FavouriteDishDtoFromJSON),
    pages: json['pages'],
  };
}

export function FavouriteDishListDtoToJSON(value?: FavouriteDishListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(FavouriteDishDtoToJSON),
    pages: value.pages,
  };
}
