/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  FavouriteRestaurantDto,
  FavouriteRestaurantDtoFromJSON,
  FavouriteRestaurantDtoFromJSONTyped,
  FavouriteRestaurantDtoToJSON,
} from './FavouriteRestaurantDto';

/**
 *
 * @export
 * @interface FavouriteRestaurantListDto
 */
export interface FavouriteRestaurantListDto {
  /**
   *
   * @type {Array<FavouriteRestaurantDto>}
   * @memberof FavouriteRestaurantListDto
   */
  data: Array<FavouriteRestaurantDto>;
  /**
   *
   * @type {number}
   * @memberof FavouriteRestaurantListDto
   */
  pages: number;
}

export function FavouriteRestaurantListDtoFromJSON(json: any): FavouriteRestaurantListDto {
  return FavouriteRestaurantListDtoFromJSONTyped(json, false);
}

export function FavouriteRestaurantListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FavouriteRestaurantListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(FavouriteRestaurantDtoFromJSON),
    pages: json['pages'],
  };
}

export function FavouriteRestaurantListDtoToJSON(value?: FavouriteRestaurantListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(FavouriteRestaurantDtoToJSON),
    pages: value.pages,
  };
}
