/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FavouriteRestaurantDto
 */
export interface FavouriteRestaurantDto {
  /**
   *
   * @type {string}
   * @memberof FavouriteRestaurantDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FavouriteRestaurantDto
   */
  name: string;
}

export function FavouriteRestaurantDtoFromJSON(json: any): FavouriteRestaurantDto {
  return FavouriteRestaurantDtoFromJSONTyped(json, false);
}

export function FavouriteRestaurantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavouriteRestaurantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function FavouriteRestaurantDtoToJSON(value?: FavouriteRestaurantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
