/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IngredientDto
 */
export interface IngredientDto {
  /**
   *
   * @type {string}
   * @memberof IngredientDto
   */
  name: string;
  /**
   *
   * @type {boolean}
   * @memberof IngredientDto
   */
  canBeExcluded: boolean;
}

export function IngredientDtoFromJSON(json: any): IngredientDto {
  return IngredientDtoFromJSONTyped(json, false);
}

export function IngredientDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    canBeExcluded: json['canBeExcluded'],
  };
}

export function IngredientDtoToJSON(value?: IngredientDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    canBeExcluded: value.canBeExcluded,
  };
}
