/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NutritionalValueDto
 */
export interface NutritionalValueDto {
  /**
   *
   * @type {number}
   * @memberof NutritionalValueDto
   */
  per100g: number;
  /**
   *
   * @type {number}
   * @memberof NutritionalValueDto
   */
  perPortion: number;
}

export function NutritionalValueDtoFromJSON(json: any): NutritionalValueDto {
  return NutritionalValueDtoFromJSONTyped(json, false);
}

export function NutritionalValueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutritionalValueDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    per100g: json['per100g'],
    perPortion: json['perPortion'],
  };
}

export function NutritionalValueDtoToJSON(value?: NutritionalValueDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    per100g: value.per100g,
    perPortion: value.perPortion,
  };
}
