/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderDishDto
 */
export interface OrderDishDto {
  /**
   *
   * @type {string}
   * @memberof OrderDishDto
   */
  dishId: string;
  /**
   *
   * @type {number}
   * @memberof OrderDishDto
   */
  count: number;
  /**
   *
   * @type {Array<string>}
   * @memberof OrderDishDto
   */
  excludedIngredients: Array<string>;
}

export function OrderDishDtoFromJSON(json: any): OrderDishDto {
  return OrderDishDtoFromJSONTyped(json, false);
}

export function OrderDishDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDishDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dishId: json['dishId'],
    count: json['count'],
    excludedIngredients: json['excludedIngredients'],
  };
}

export function OrderDishDtoToJSON(value?: OrderDishDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dishId: value.dishId,
    count: value.count,
    excludedIngredients: value.excludedIngredients,
  };
}
