/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterAsPartnerDto
 */
export interface RegisterAsPartnerDto {
  /**
   * RFC 5322 standard email format
   * @type {string}
   * @memberof RegisterAsPartnerDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterAsPartnerDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof RegisterAsPartnerDto
   */
  phoneNumber: string;
  /**
   * Polish NIP number
   * @type {string}
   * @memberof RegisterAsPartnerDto
   */
  nip: string;
}

export function RegisterAsPartnerDtoFromJSON(json: any): RegisterAsPartnerDto {
  return RegisterAsPartnerDtoFromJSONTyped(json, false);
}

export function RegisterAsPartnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAsPartnerDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    phoneNumber: json['phoneNumber'],
    nip: json['nip'],
  };
}

export function RegisterAsPartnerDtoToJSON(value?: RegisterAsPartnerDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    phoneNumber: value.phoneNumber,
    nip: value.nip,
  };
}
