/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterAsUserDto
 */
export interface RegisterAsUserDto {
  /**
   * RFC 5322 standard email format
   * @type {string}
   * @memberof RegisterAsUserDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterAsUserDto
   */
  password: string;
}

export function RegisterAsUserDtoFromJSON(json: any): RegisterAsUserDto {
  return RegisterAsUserDtoFromJSONTyped(json, false);
}

export function RegisterAsUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAsUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function RegisterAsUserDtoToJSON(value?: RegisterAsUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
