/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { RestaurantDto, RestaurantDtoFromJSON, RestaurantDtoFromJSONTyped, RestaurantDtoToJSON } from './RestaurantDto';

/**
 *
 * @export
 * @interface RestaurantListDto
 */
export interface RestaurantListDto {
  /**
   *
   * @type {Array<RestaurantDto>}
   * @memberof RestaurantListDto
   */
  data: Array<RestaurantDto>;
  /**
   *
   * @type {number}
   * @memberof RestaurantListDto
   */
  pages: number;
}

export function RestaurantListDtoFromJSON(json: any): RestaurantListDto {
  return RestaurantListDtoFromJSONTyped(json, false);
}

export function RestaurantListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(RestaurantDtoFromJSON),
    pages: json['pages'],
  };
}

export function RestaurantListDtoToJSON(value?: RestaurantListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(RestaurantDtoToJSON),
    pages: value.pages,
  };
}
