/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RestaurantTagEnum = {
  FastFood: 'fast food',
  Wegaska: 'wegańska',
  Wegetariaska: 'wegetariańska',
  Kawiarnia: 'kawiarnia',
  Zdrowa: 'zdrowa',
  StreetFood: 'street food',
  Desery: 'desery',
  Pizza: 'pizza',
  Burgery: 'burgery',
  Sushi: 'sushi',
  Kebab: 'kebab',
  GlutenFree: 'gluten free',
} as const;
export type RestaurantTagEnum = typeof RestaurantTagEnum[keyof typeof RestaurantTagEnum];

export function RestaurantTagEnumFromJSON(json: any): RestaurantTagEnum {
  return RestaurantTagEnumFromJSONTyped(json, false);
}

export function RestaurantTagEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantTagEnum {
  return json as RestaurantTagEnum;
}

export function RestaurantTagEnumToJSON(value?: RestaurantTagEnum | null): any {
  return value as any;
}
