/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { OrderDishDto, OrderDishDtoFromJSON, OrderDishDtoFromJSONTyped, OrderDishDtoToJSON } from './OrderDishDto';

/**
 *
 * @export
 * @interface SubOrderDto
 */
export interface SubOrderDto {
  /**
   *
   * @type {Date}
   * @memberof SubOrderDto
   */
  deliveryDate: Date;
  /**
   *
   * @type {number}
   * @memberof SubOrderDto
   */
  hourStart: number;
  /**
   *
   * @type {number}
   * @memberof SubOrderDto
   */
  hourEnd: number;
  /**
   *
   * @type {Array<OrderDishDto>}
   * @memberof SubOrderDto
   */
  dishes: Array<OrderDishDto>;
}

export function SubOrderDtoFromJSON(json: any): SubOrderDto {
  return SubOrderDtoFromJSONTyped(json, false);
}

export function SubOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubOrderDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    deliveryDate: new Date(json['deliveryDate']),
    hourStart: json['hourStart'],
    hourEnd: json['hourEnd'],
    dishes: (json['dishes'] as Array<any>).map(OrderDishDtoFromJSON),
  };
}

export function SubOrderDtoToJSON(value?: SubOrderDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    deliveryDate: value.deliveryDate.toISOString(),
    hourStart: value.hourStart,
    hourEnd: value.hourEnd,
    dishes: (value.dishes as Array<any>).map(OrderDishDtoToJSON),
  };
}
