/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  CuisineTypeEnum,
  CuisineTypeEnumFromJSON,
  CuisineTypeEnumFromJSONTyped,
  CuisineTypeEnumToJSON,
} from './CuisineTypeEnum';
import {
  OperationalCityEnum,
  OperationalCityEnumFromJSON,
  OperationalCityEnumFromJSONTyped,
  OperationalCityEnumToJSON,
} from './OperationalCityEnum';
import {
  RestaurantTagEnum,
  RestaurantTagEnumFromJSON,
  RestaurantTagEnumFromJSONTyped,
  RestaurantTagEnumToJSON,
} from './RestaurantTagEnum';

/**
 *
 * @export
 * @interface UpdatePartnerProfileDto
 */
export interface UpdatePartnerProfileDto {
  /**
   *
   * @type {string}
   * @memberof UpdatePartnerProfileDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePartnerProfileDto
   */
  description?: string;
  /**
   *
   * @type {Array<CuisineTypeEnum>}
   * @memberof UpdatePartnerProfileDto
   */
  cuisineType: Array<CuisineTypeEnum>;
  /**
   *
   * @type {Array<RestaurantTagEnum>}
   * @memberof UpdatePartnerProfileDto
   */
  tags: Array<RestaurantTagEnum>;
  /**
   *
   * @type {Array<OperationalCityEnum>}
   * @memberof UpdatePartnerProfileDto
   */
  operationalCities: Array<OperationalCityEnum>;
  /**
   *
   * @type {string}
   * @memberof UpdatePartnerProfileDto
   */
  bankAccountNumber?: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePartnerProfileDto
   */
  phoneNumber?: string;
}

export function UpdatePartnerProfileDtoFromJSON(json: any): UpdatePartnerProfileDto {
  return UpdatePartnerProfileDtoFromJSONTyped(json, false);
}

export function UpdatePartnerProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePartnerProfileDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    cuisineType: (json['cuisineType'] as Array<any>).map(CuisineTypeEnumFromJSON),
    tags: (json['tags'] as Array<any>).map(RestaurantTagEnumFromJSON),
    operationalCities: (json['operationalCities'] as Array<any>).map(OperationalCityEnumFromJSON),
    bankAccountNumber: !exists(json, 'bankAccountNumber') ? undefined : json['bankAccountNumber'],
    phoneNumber: !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
  };
}

export function UpdatePartnerProfileDtoToJSON(value?: UpdatePartnerProfileDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    cuisineType: (value.cuisineType as Array<any>).map(CuisineTypeEnumToJSON),
    tags: (value.tags as Array<any>).map(RestaurantTagEnumToJSON),
    operationalCities: (value.operationalCities as Array<any>).map(OperationalCityEnumToJSON),
    bankAccountNumber: value.bankAccountNumber,
    phoneNumber: value.phoneNumber,
  };
}
