/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { CardDto, CardDtoFromJSON, CardDtoFromJSONTyped, CardDtoToJSON } from './CardDto';

/**
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  surname?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  phoneNumber?: string;
  /**
   *
   * @type {CardDto}
   * @memberof UpdateUserDto
   */
  card?: CardDto;
}

export function UpdateUserDtoFromJSON(json: any): UpdateUserDto {
  return UpdateUserDtoFromJSONTyped(json, false);
}

export function UpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    surname: !exists(json, 'surname') ? undefined : json['surname'],
    phoneNumber: !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    card: !exists(json, 'card') ? undefined : CardDtoFromJSON(json['card']),
  };
}

export function UpdateUserDtoToJSON(value?: UpdateUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    surname: value.surname,
    phoneNumber: value.phoneNumber,
    card: CardDtoToJSON(value.card),
  };
}
