### register
POST {{baseUrl}}/auth/register/partner

{
  "email": "partner@email.com",
  "password": "Password1",
  "phoneNumber": "800500300",
  "nip": "1234563218"
}

### login
POST {{baseUrl}}/auth/login

{
  "email": "partner@email.com",
  "role": "Partner",
  "password": "Password1",
  "rememberMe": false
}

### complete the profile
PUT {{baseUrl}}/partner/profile

{
  "name": "Resto bar",
  "description": "Opis restauracji.",
  "cuisineType": [
    "włoska"
  ],
  "tags": [
    "pizza",
    "zdrowa"
  ],
  "bankAccountNumber": "72920080748556126838146923",
  "phoneNumber": "800500300"
}

### add an address
POST {{baseUrl}}/partner/addresses

{
  "street": "Street",
  "streetNumber": "1A",
  "apartmentNumber": "1",
  "floor": "1",
  "city": "City",
  "postcode": "00-000"
}

### add a dish
POST {{baseUrl}}/partner/dishes

{
  "name": "Danie 1",
  "mealType": [
    "lunch",
    "obiad"
  ],
  "description": "Opis dania",
  "price": 2350,
  "tags": [
    "ostre",
    "gluten free"
  ],
  "ingredients": [
    {
      "name": "bazylia",
      "canBeExcluded": false
    }
  ],
  "allergens": [
    "orzechy"
  ],
  "portionWeight": 0,
  "calories": {
    "per100g": 0,
    "perPortion": 0
  },
  "fats": {
    "per100g": 0,
    "perPortion": 0
  },
  "proteins": {
    "per100g": 0,
    "perPortion": 0
  },
  "carbohydrates": {
    "per100g": 0,
    "perPortion": 0
  }
}

### logout
POST {{baseUrl}}/auth/logout
