
@articlesUrl = {{baseUrl}}/articles

### get all articles
GET {{articlesUrl}}

### create article
# @name create_article
POST {{articlesUrl}}/

{
  "title": "Article title",
  "content": "Article content"
}

###
@article_id = {{create_article.response.body.id}}

### get article by id
GET {{articlesUrl}}/{{article_id}}


### update article
PUT {{articlesUrl}}/{{article_id}}

{
  "title":"addsd",
  "content": "Article content"
}

### delete article
DELETE {{articlesUrl}}/{{article_id}}