@authUrl = {{baseUrl}}/auth
@usersUrl = {{baseUrl}}/users

### register as user
POST {{authUrl}}/register/user

{
  "email": "user@email.com",
  "password": "Password1"
}

### login
POST {{authUrl}}/login

{
  "email": "user@email.com",
  "role": "User",
  "password": "Password1",
  "rememberMe": false
}

### get user's profile
GET {{usersUrl}}/profile

### update user's profile
PUT {{usersUrl}}/profile

{
  "name": "John",
  "surname": "Doe"
}
