/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  ArticleDto,
  ArticleDtoFromJSON,
  ArticleDtoToJSON,
  ArticleListDto,
  ArticleListDtoFromJSON,
  ArticleListDtoToJSON,
  CreateArticleDto,
  CreateArticleDtoFromJSON,
  CreateArticleDtoToJSON,
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  UpdateArticleDto,
  UpdateArticleDtoFromJSON,
  UpdateArticleDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface DeleteRequest {
  id: string;
}

export interface CreateRequest {
  createArticleDto: CreateArticleDto;
}

export interface FindByIdRequest {
  id: string;
}

export interface ListRequest {
  page?: number;
  limit?: number;
}

export interface UpdateRequest {
  id: string;
  updateArticleDto: UpdateArticleDto;
}

/**
 *
 */
export class ArticlesApi extends runtime.BaseAPI {
  /**
   * Delete a article.
   */
  async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling _delete.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/articles/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a article.
   */
  async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit): Promise<void> {
    await this._deleteRaw(requestParameters, initOverrides);
  }

  /**
   * Create a new article.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<ArticleDto>> {
    if (requestParameters.createArticleDto === null || requestParameters.createArticleDto === undefined) {
      throw new runtime.RequiredError(
        'createArticleDto',
        'Required parameter requestParameters.createArticleDto was null or undefined when calling create.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/articles`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateArticleDtoToJSON(requestParameters.createArticleDto),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArticleDtoFromJSON(jsonValue));
  }

  /**
   * Create a new article.
   */
  async create(requestParameters: CreateRequest, initOverrides?: RequestInit): Promise<ArticleDto> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Retrive a article by id.
   */
  async findByIdRaw(
    requestParameters: FindByIdRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<ArticleDto>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling findById.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/articles/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArticleDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a article by id.
   */
  async findById(requestParameters: FindByIdRequest, initOverrides?: RequestInit): Promise<ArticleDto> {
    const response = await this.findByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Retrive a list of articles.
   */
  async listRaw(
    requestParameters: ListRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<ArticleListDto>> {
    const queryParameters: any = {};

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/articles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArticleListDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a list of articles.
   */
  async list(requestParameters: ListRequest = {}, initOverrides?: RequestInit): Promise<ArticleListDto> {
    const response = await this.listRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update an existing article.
   */
  async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling update.',
      );
    }

    if (requestParameters.updateArticleDto === null || requestParameters.updateArticleDto === undefined) {
      throw new runtime.RequiredError(
        'updateArticleDto',
        'Required parameter requestParameters.updateArticleDto was null or undefined when calling update.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/articles/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateArticleDtoToJSON(requestParameters.updateArticleDto),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update an existing article.
   */
  async update(requestParameters: UpdateRequest, initOverrides?: RequestInit): Promise<void> {
    await this.updateRaw(requestParameters, initOverrides);
  }
}
