/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  CreateOrderDto,
  CreateOrderDtoFromJSON,
  CreateOrderDtoToJSON,
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  OrderDto,
  OrderDtoFromJSON,
  OrderDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface OrdersApiCreateRequest {
  createOrderDto: CreateOrderDto;
}

/**
 *
 */
export class OrdersApi extends runtime.BaseAPI {
  /**
   * Create a new order.
   */
  async createRaw(
    requestParameters: OrdersApiCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<runtime.ApiResponse<OrderDto>> {
    if (requestParameters.createOrderDto === null || requestParameters.createOrderDto === undefined) {
      throw new runtime.RequiredError(
        'createOrderDto',
        'Required parameter requestParameters.createOrderDto was null or undefined when calling create.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/orders`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateOrderDtoToJSON(requestParameters.createOrderDto),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OrderDtoFromJSON(jsonValue));
  }

  /**
   * Create a new order.
   */
  async create(
    requestParameters: OrdersApiCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<OrderDto> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
