/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  PartnerProfileDto,
  PartnerProfileDtoFromJSON,
  PartnerProfileDtoToJSON,
  UpdatePartnerProfileDto,
  UpdatePartnerProfileDtoFromJSON,
  UpdatePartnerProfileDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface UpdatePartnerRequest {
  updatePartnerProfileDto: UpdatePartnerProfileDto;
}

/**
 *
 */
export class PartnersProfileApi extends runtime.BaseAPI {
  /**
   * Retrive a profile by id.
   */
  async findPartnerByIdRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<PartnerProfileDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/partner/profile`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => PartnerProfileDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a profile by id.
   */
  async findPartnerById(initOverrides?: RequestInit): Promise<PartnerProfileDto> {
    const response = await this.findPartnerByIdRaw(initOverrides);
    return await response.value();
  }

  /**
   * Update an existing profile.
   */
  async updatePartnerRaw(
    requestParameters: UpdatePartnerRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.updatePartnerProfileDto === null || requestParameters.updatePartnerProfileDto === undefined) {
      throw new runtime.RequiredError(
        'updatePartnerProfileDto',
        'Required parameter requestParameters.updatePartnerProfileDto was null or undefined when calling updatePartner.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/partner/profile`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePartnerProfileDtoToJSON(requestParameters.updatePartnerProfileDto),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update an existing profile.
   */
  async updatePartner(requestParameters: UpdatePartnerRequest, initOverrides?: RequestInit): Promise<void> {
    await this.updatePartnerRaw(requestParameters, initOverrides);
  }
}
