/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  DishDto,
  DishDtoFromJSON,
  DishDtoToJSON,
  DishListDto,
  DishListDtoFromJSON,
  DishListDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface FindRestaurantsDishByIdRequest {
  restaurantId: string;
  id: string;
}

export interface ListRestaurantsDishesRequest {
  restaurantId: string;
  page?: number;
  limit?: number;
}

/**
 *
 */
export class RestaurantsDishesApi extends runtime.BaseAPI {
  /**
   * Retrive a dish by id.
   */
  async findRestaurantsDishByIdRaw(
    requestParameters: FindRestaurantsDishByIdRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<DishDto>> {
    if (requestParameters.restaurantId === null || requestParameters.restaurantId === undefined) {
      throw new runtime.RequiredError(
        'restaurantId',
        'Required parameter requestParameters.restaurantId was null or undefined when calling findRestaurantsDishById.',
      );
    }

    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling findRestaurantsDishById.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/restaurants/{restaurantId}/dishes/{id}`
          .replace(`{${'restaurantId'}}`, encodeURIComponent(String(requestParameters.restaurantId)))
          .replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DishDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a dish by id.
   */
  async findRestaurantsDishById(
    requestParameters: FindRestaurantsDishByIdRequest,
    initOverrides?: RequestInit,
  ): Promise<DishDto> {
    const response = await this.findRestaurantsDishByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Retrive a list of dishes.
   */
  async listRestaurantsDishesRaw(
    requestParameters: ListRestaurantsDishesRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<DishListDto>> {
    if (requestParameters.restaurantId === null || requestParameters.restaurantId === undefined) {
      throw new runtime.RequiredError(
        'restaurantId',
        'Required parameter requestParameters.restaurantId was null or undefined when calling listRestaurantsDishes.',
      );
    }

    const queryParameters: any = {};

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/restaurants/{restaurantId}/dishes`.replace(
          `{${'restaurantId'}}`,
          encodeURIComponent(String(requestParameters.restaurantId)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DishListDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a list of dishes.
   */
  async listRestaurantsDishes(
    requestParameters: ListRestaurantsDishesRequest,
    initOverrides?: RequestInit,
  ): Promise<DishListDto> {
    const response = await this.listRestaurantsDishesRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
