/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  DishListDto,
  DishListDtoFromJSON,
  DishListDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface RestaurantsDishesApiListRequest {
  restaurantId: string;
  city?: string;
  cuisineType?: Array<string>;
  mealType?: Array<string>;
  tags?: Array<string>;
  page?: number;
  limit?: number;
}

/**
 *
 */
export class RestaurantsDishesApi extends runtime.BaseAPI {
  /**
   * Retrieve a list of dishes.
   */
  async listRaw(
    requestParameters: RestaurantsDishesApiListRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<DishListDto>> {
    if (requestParameters.restaurantId === null || requestParameters.restaurantId === undefined) {
      throw new runtime.RequiredError(
        'restaurantId',
        'Required parameter requestParameters.restaurantId was null or undefined when calling list.',
      );
    }

    const queryParameters: any = {};

    if (requestParameters.city !== undefined) {
      queryParameters['city'] = requestParameters.city;
    }

    if (requestParameters.cuisineType) {
      queryParameters['cuisineType'] = requestParameters.cuisineType;
    }

    if (requestParameters.mealType) {
      queryParameters['mealType'] = requestParameters.mealType;
    }

    if (requestParameters.tags) {
      queryParameters['tags'] = requestParameters.tags;
    }

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/restaurants/{restaurantId}/dishes`.replace(
          `{${'restaurantId'}}`,
          encodeURIComponent(String(requestParameters.restaurantId)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DishListDtoFromJSON(jsonValue));
  }

  /**
   * Retrieve a list of dishes.
   */
  async list(requestParameters: RestaurantsDishesApiListRequest, initOverrides?: RequestInit): Promise<DishListDto> {
    const response = await this.listRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
