/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  CuisineTypeEnum,
  CuisineTypeEnumFromJSON,
  CuisineTypeEnumToJSON,
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  OperationalCityEnum,
  OperationalCityEnumFromJSON,
  OperationalCityEnumToJSON,
  RestaurantDto,
  RestaurantDtoFromJSON,
  RestaurantDtoToJSON,
  RestaurantListDto,
  RestaurantListDtoFromJSON,
  RestaurantListDtoToJSON,
  RestaurantTagEnum,
  RestaurantTagEnumFromJSON,
  RestaurantTagEnumToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface RestaurantsApiFindByIdRequest {
  id: string;
}

export interface RestaurantsApiListRequest {
  city?: OperationalCityEnum;
  cuisineType?: Array<CuisineTypeEnum>;
  tags?: Array<RestaurantTagEnum>;
  page?: number;
  limit?: number;
}

/**
 *
 */
export class RestaurantsApi extends runtime.BaseAPI {
  /**
   * Retrieve a restaurant by id.
   */
  async findByIdRaw(
    requestParameters: RestaurantsApiFindByIdRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<RestaurantDto>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling findById.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/restaurants/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters.id))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => RestaurantDtoFromJSON(jsonValue));
  }

  /**
   * Retrieve a restaurant by id.
   */
  async findById(
    requestParameters: RestaurantsApiFindByIdRequest,
    initOverrides?: RequestInit,
  ): Promise<RestaurantDto> {
    const response = await this.findByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Retrieve a list of restaurants.
   */
  async listRaw(
    requestParameters: RestaurantsApiListRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<RestaurantListDto>> {
    const queryParameters: any = {};

    if (requestParameters.city !== undefined) {
      queryParameters['city'] = requestParameters.city;
    }

    if (requestParameters.cuisineType) {
      queryParameters['cuisineType'] = requestParameters.cuisineType;
    }

    if (requestParameters.tags) {
      queryParameters['tags'] = requestParameters.tags;
    }

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/restaurants`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => RestaurantListDtoFromJSON(jsonValue));
  }

  /**
   * Retrieve a list of restaurants.
   */
  async list(
    requestParameters: RestaurantsApiListRequest = {},
    initOverrides?: RequestInit,
  ): Promise<RestaurantListDto> {
    const response = await this.listRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
