/* tslint:disable */
/* eslint-disable */
/**
 * JeszCoChcesz API 🍲🍝🍜
 * JeszCoChcesz is an online food delivery system connecting restaurants with health-conscious users.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  UpdateUserDto,
  UpdateUserDtoFromJSON,
  UpdateUserDtoToJSON,
  UserDto,
  UserDtoFromJSON,
  UserDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface UserssProfileApiUpdateRequest {
  updateUserDto: UpdateUserDto;
}

/**
 *
 */
export class UserssProfileApi extends runtime.BaseAPI {
  /**
   * Retrieve a user by id.
   */
  async findByIdRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<UserDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/users/profile`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserDtoFromJSON(jsonValue));
  }

  /**
   * Retrieve a user by id.
   */
  async findById(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<UserDto> {
    const response = await this.findByIdRaw(initOverrides);
    return await response.value();
  }

  /**
   * Update an existing user.
   */
  async updateRaw(
    requestParameters: UserssProfileApiUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.updateUserDto === null || requestParameters.updateUserDto === undefined) {
      throw new runtime.RequiredError(
        'updateUserDto',
        'Required parameter requestParameters.updateUserDto was null or undefined when calling update.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/users/profile`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserDtoToJSON(requestParameters.updateUserDto),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update an existing user.
   */
  async update(
    requestParameters: UserssProfileApiUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<void> {
    await this.updateRaw(requestParameters, initOverrides);
  }
}
