/* tslint:disable */
/* eslint-disable */
/**
 * App example
 * The app API description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  FavouriteRestaurantListDto,
  FavouriteRestaurantListDtoFromJSON,
  FavouriteRestaurantListDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

export interface ListFavouriteRestaurantsRequest {
  page?: number;
  limit?: number;
}

/**
 *
 */
export class UsersFavouriteRestaurantsApi extends runtime.BaseAPI {
  /**
   * Retrive a list of restaurants.
   */
  async listFavouriteRestaurantsRaw(
    requestParameters: ListFavouriteRestaurantsRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<FavouriteRestaurantListDto>> {
    const queryParameters: any = {};

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/users/favourite/restaurants`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => FavouriteRestaurantListDtoFromJSON(jsonValue));
  }

  /**
   * Retrive a list of restaurants.
   */
  async listFavouriteRestaurants(
    requestParameters: ListFavouriteRestaurantsRequest = {},
    initOverrides?: RequestInit,
  ): Promise<FavouriteRestaurantListDto> {
    const response = await this.listFavouriteRestaurantsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
